import { Analytics } from "@vercel/analytics/react";
import type { Metadata } from "next";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar/NavigationBar";
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="color-scheme" content="light only" />
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body>
        <div className=" sticky top-0 left-0 z-10">
          <NavigationBar />
        </div>

        {children}
        <Footer
          isVisible={true}
          backgroudnColor="from-colorSix to-colorSeven"
          fontColor=" text-black"
        />
        <Analytics />
      </body>
    </html>
  );
}
